env:
  - GO111MODULE=on
  - GOPROXY=https://gocenter.io
builds:
  - main: cmd/kubenab/main.go
    binary: kubenab
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    flags:
      - -tags 'strip_debug'
      -  --snapshot --skip-publish --rm-dist
archives:
  - format: tar.gz
    name_template: "kubenab_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
