resources:
  - name: kubenab_release
    type: GitRepo
    configuration:
      gitProvider: rimas_github
      path: rimusz/kubenab
      files:
        exclude: .pipelines/.*.yml$
      branches:
        include: master
      tags:
        include: .*.*.*
      buildOn:
        commit: true
        tagCreate: true

pipelines:
  - name: kubenabRelease
    steps:
      - name: build_image
        type: DockerBuild
        configuration:
          #nodePool: k8s-dynamic-pool
          affinityGroup: kubenabGroup
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: kubenab
          dockerImageTag: test
          inputResources:
            - name: kubenab_release
      - name: buildGo
        type: Bash
        configuration:
          #nodePool: k8s-dynamic-pool
          affinityGroup: kubenabGroup
          runtime:
            type: image
            image:
              custom:
                name: golang
                tag: 1.13.9
                autoPull: true
          environmentVariables:
            TAG_NAME: test
            GO111MODULE: on
            GOPROXY: https://gocenter.io
            CGO_ENABLED: 0
          inputResources:
            - name: kubenab_release
              trigger: false
          integrations:
            - name: rimas_github
          inputSteps:
            - name: build_image
        execution:
          onExecute:
            - cd $res_kubenab_release_resourcePath
            - ls
            - cd cmd/kubenab
            - go mod download
            - go build
 
