resources:
  - name: kubenab_release
    type: GitRepo
    configuration:
      gitProvider: rimas_github
      path: rimusz/kubenab
      files:
        exclude: .pipelines/.*.yml$
      branches:
        include: master
      tags:
        include: .*.*.*
      buildOn:
        commit: true
        tagCreate: true

pipelines:
  - name: kubenabRelease
    steps:
      - name: build_image
        type: DockerBuild
        configuration:
          affinityGroup: bldGroup
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: kubenab
          dockerImageTag: $run_number
          inputResources:
            - name: kubenab_release
      - name: goreleaser
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: golang
                tag: 1.13-stretch
                autoPull: false
          environmentVariables:
            TAG_NAME: $run_number
          inputResources:
            - name: kubenab_release
              trigger: false
          integrations:
            - name: rimas_github
          inputSteps:
            - name: build_image
        execution:
          onExecute:
            - cd $res_kubenab_release_resourcePath
            - ls
            - pwd
            - curl -sL https://raw.githubusercontent.com/goreleaser/get/master/get | VERSION=v0.127.0 bash
            - echo "goreleaser finished!!!"
